# CREAR LISTA
LISTA = (["cereza","pera","melon","zandia"])
LISTA = (["cereza","pera","melon","zandia","mango"])
LISTA.insert(0,"uva")
# longitud de la lista
#ULTIMA_LISTA = LISTA.pop()
#for LISTA in LISTA:
   # print(f"LISTA  {LISTA}. Longitud {len(LISTA)}")

print("------------------------------------------")
# Imprimer nombres que contengan mas de 5 letras : CEREZA, PERA, MELON, ZANDIA, MANGO, UVA
#for LISTA in LISTA:
   # if len(LISTA) > 5:
        #print(LISTA)

LISTA.clear()
print(LISTA)